CREATE DATABASE SPOT_DB;

USE SPOT_DB;

SELECT * FROM MUSICS_TB;

	INSERT INTO MUSICS_TB(ID_ARTIST, NM_MUSIC, IMG_COVER)
				VALUES(1, 'Pericles', 'AAAAAA.JPG');


		SELECT  	NM_MUSIC    AS MUSIC,
					NM_ARTIST   AS ARTIST
			FROM MUSICS_TB      MUSICS
        INNER JOIN ARTISTS_TB   ARTISTS ON MUSICS.NM_ARTIST = ARTISTS.NM_ARTIST;
        
